name: Approaching 50
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#ff7c6e'
    - '#53729a'
    - '#ffbf61'
  brandStrength: 0.5
  lightness: 0.7132028338965029
  saturation: 0.9212684077210724
  rhythmicContrast: 0.5978127089329064
purpose: []
